default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'postgres' %>  # Название хоста должно совпадать с названием сервиса в docker-compose
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>

development:
  <<: *default
  database: bbq_development

test:
  <<: *default
  database: bbq_test

production:
  <<: *default
  database: bbq_production

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
