# .docker/docker-compose.yml
version: '3.8'
services:
  app:
    container_name: bbq
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: ["rails", "server", "-b", "0.0.0.0"]

  postgres:
    container_name: postgres_bbq
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ../tmp/db/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
