name: Rails CI with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start services
        run: |
          docker-compose -f .docker/docker-compose.yml up -d postgres
          docker-compose -f .docker/docker-compose.yml up -d app

      - name: Run RSpec tests
        run: |
          docker-compose -f .docker/docker-compose.yml exec -T app bundle exec rails db:create
          docker-compose -f .docker/docker-compose.yml exec -T app bundle exec rails db:migrate
          docker-compose -f .docker/docker-compose.yml exec -T app bundle exec rspec spec/controllers --format=d
          docker-compose -f .docker/docker-compose.yml exec -T app bundle exec rspec spec/jobs --format=d
          docker-compose -f .docker/docker-compose.yml exec -T app bundle exec rspec spec/policies --format=d

        env:
          RAILS_ENV: test
